const options = [
    // { value: 'dummyText', label: 'dummyText' },
    { value: 'Sydney', label: 'Sydney' },
    { value: 'Melbourne', label: 'Melbourne' },
    { value: 'Brisbane', label: 'Brisbane' },
    { value: 'Perth', label: 'Perth' },
    { value: 'Adelaide', label: 'Adelaide' },
    { value: 'Gold Coast', label: 'Gold Coast' },
    { value: 'Cranbourne', label: 'Cranbourne' },
    { value: 'Canberra', label: 'Canberra' },
    { value: 'Newcastle', label: 'Newcastle' },
    { value: 'Wollongong', label: 'Wollongong' },
    { value: 'Geelong', label: 'Geelong' },
    { value: 'Hobart', label: 'Hobart' },
    { value: 'Townsville', label: 'Townsville' },
    { value: 'Ipswich', label: 'Ipswich' },
    { value: 'Cairns', label: 'Cairns' },
    { value: 'Toowoomba', label: 'Toowoomba' },
    { value: 'Darwin', label: 'Darwin' },
    { value: 'Ballarat', label: 'Ballarat' },
    { value: 'Bendigo', label: 'Bendigo' },
    { value: 'Launceston', label: 'Launceston' },
    { value: 'Mackay', label: 'Mackay' },
    { value: 'Rockhampton', label: 'Rockhampton' },
    { value: 'Maitland', label: 'Maitland' },
    { value: 'Bunbury', label: 'Bunbury' },
    { value: 'Coffs Harbour', label: 'Coffs Harbour' },
    { value: 'Bundaberg', label: 'Bundaberg' },
    { value: 'Wagga Wagga', label: 'Wagga Wagga' },
    { value: 'Hervey Bay', label: 'Hervey Bay' },
    { value: 'Shepparton', label: 'Shepparton' },
    { value: 'Albury', label: 'Albury' },
    { value: 'Port Macquarie', label: 'Port Macquarie' },
    { value: 'Pakenham', label: 'Pakenham' },
    { value: 'Tamworth', label: 'Tamworth' },
    { value: 'Caloundra', label: 'Caloundra' },
    { value: 'Orange', label: 'Orange' },
    { value: 'Dubbo', label: 'Dubbo' },
    { value: 'Geraldton', label: 'Geraldton' },
    { value: 'Nowra', label: 'Nowra' },
    { value: 'Bathurst', label: 'Bathurst' },
    { value: 'Queanbeyan', label: 'Queanbeyan' },
    { value: 'Frankston', label: 'Frankston' },
    { value: 'Sunbury', label: 'Sunbury' },
    { value: 'Warrnambool', label: 'Warrnambool' },
    { value: 'Wodonga', label: 'Wodonga' },
    { value: 'Albany', label: 'Albany' },
    { value: 'Gladstone', label: 'Gladstone' },
    { value: 'Mildura', label: 'Mildura' },
    { value: 'Southport', label: 'Southport' },
    { value: 'Alice Springs', label: 'Alice Springs' },
    { value: 'Dandenong', label: 'Dandenong' },
    { value: 'Kalgoorlie', label: 'Kalgoorlie' },
    { value: 'Mount Gambier', label: 'Mount Gambier' },
    { value: 'Lismore', label: 'Lismore' },
    { value: 'Maryborough', label: 'Maryborough' },
    { value: 'Quakers Hill', label: 'Quakers Hill' },
    { value: 'Gawler', label: 'Gawler' },
    { value: 'Caboolture', label: 'Caboolture' },
    { value: 'Ballina', label: 'Ballina' },
    { value: 'Taree', label: 'Taree' },
    { value: 'Traralgon', label: 'Traralgon' },
    { value: 'Busselton', label: 'Busselton' },
    { value: 'Armidale', label: 'Armidale' },
    { value: 'Goulburn', label: 'Goulburn' },
    { value: 'Devonport', label: 'Devonport' },
    { value: 'Bacchus Marsh', label: 'Bacchus Marsh' },
    { value: 'Whyalla', label: 'Whyalla' },
    { value: 'Cessnock', label: 'Cessnock' },
    { value: 'Gympie', label: 'Gympie' },
    { value: 'Griffith', label: 'Griffith' },
    { value: 'Kwinana', label: 'Kwinana' },
    { value: 'Burnie', label: 'Burnie' },
    { value: 'Wangaratta', label: 'Wangaratta' },
    { value: 'Grafton', label: 'Grafton' },
    { value: 'Yeppoon', label: 'Yeppoon' },
    { value: 'Murray Bridge', label: 'Murray Bridge' },
    { value: 'Mount Isa', label: 'Mount Isa' },
    { value: 'Narangba', label: 'Narangba' },
    { value: 'Mount Eliza', label: 'Mount Eliza' },
    { value: 'Broken Hill', label: 'Broken Hill' },
    { value: 'Nerang', label: 'Nerang' },
    { value: 'Karratha', label: 'Karratha' },
    { value: 'Mount Barker', label: 'Mount Barker' },
    { value: 'Horsham', label: 'Horsham' },
    { value: 'Lara', label: 'Lara' },
    { value: 'Singleton', label: 'Singleton' },
    { value: 'Port Lincoln', label: 'Port Lincoln' },
    { value: 'Banora Point', label: 'Banora Point' },
    { value: 'Warwick', label: 'Warwick' },
    { value: 'Rochedale', label: 'Rochedale' },
    { value: 'Kempsey', label: 'Kempsey' },
    { value: 'Ulladulla', label: 'Ulladulla' },
    { value: 'Sale', label: 'Sale' },
    { value: 'Echuca', label: 'Echuca' },
    { value: 'Australind', label: 'Australind' },
    { value: 'Broome', label: 'Broome' },
    { value: 'Port Hedland', label: 'Port Hedland' },
    { value: 'Warragul', label: 'Warragul' },
    { value: 'Port Pirie', label: 'Port Pirie' },
    { value: 'Barwon Heads', label: 'Barwon Heads' },
    { value: 'Emerald', label: 'Emerald' },
    { value: 'Ulverstone', label: 'Ulverstone' },
    { value: 'Morwell', label: 'Morwell' },
    { value: 'Gisborne', label: 'Gisborne' },
    { value: 'Port Augusta', label: 'Port Augusta' },
    { value: 'Forster', label: 'Forster' },
    { value: 'Penrith', label: 'Penrith' },
    { value: 'Torquay', label: 'Torquay' },
    { value: 'Jimboomba', label: 'Jimboomba' },
    { value: 'Lithgow', label: 'Lithgow' },
    { value: 'Bowral', label: 'Bowral' },
    { value: 'Goonellabah', label: 'Goonellabah' },
    { value: 'Raymond Terrace', label: 'Raymond Terrace' },
    { value: 'Leopold', label: 'Leopold' },
    { value: 'Dalby', label: 'Dalby' },
    { value: 'Campbelltown', label: 'Campbelltown' },
    { value: 'Colac', label: 'Colac' },
    { value: 'Muswellbrook', label: 'Muswellbrook' },
    { value: 'Esperance', label: 'Esperance' },
    { value: 'Drouin', label: 'Drouin' },
    { value: 'Rutherford', label: 'Rutherford' },
    { value: 'Nelson Bay', label: 'Nelson Bay' },
    { value: 'Inverell', label: 'Inverell' },
    { value: 'Parkes', label: 'Parkes' },
    { value: 'Somerville', label: 'Somerville' },
    { value: 'Gracemere', label: 'Gracemere' },
    { value: 'Batemans Bay', label: 'Batemans Bay' },
    { value: 'Nambour', label: 'Nambour' },
    { value: 'Swan Hill', label: 'Swan Hill' },
    { value: 'Mareeba', label: 'Mareeba' },
    { value: 'Corinda', label: 'Corinda' },
    { value: 'Samford', label: 'Samford' },
    { value: 'Mudgee', label: 'Mudgee' },
    { value: 'Casino', label: 'Casino' },
    { value: 'Portland', label: 'Portland' },
    { value: 'Kingston', label: 'Kingston' },
    { value: 'Kingaroy', label: 'Kingaroy' },
    { value: 'Kangaroo Flat', label: 'Kangaroo Flat' },
    { value: 'Bowen', label: 'Bowen' },
    { value: 'Young', label: 'Young' },
    { value: 'Cowra', label: 'Cowra' },
    { value: 'Hamilton', label: 'Hamilton' },
    { value: 'Gunnedah', label: 'Gunnedah' },
    { value: 'Mount Evelyn', label: 'Mount Evelyn' },
    { value: 'Andergrove', label: 'Andergrove' },
    { value: 'Moree', label: 'Moree' },
    { value: 'Benalla', label: 'Benalla' },
    { value: 'Currumbin', label: 'Currumbin' },
    { value: 'Wollert', label: 'Wollert' },
    { value: 'Mittagong', label: 'Mittagong' },
    { value: 'Kelso', label: 'Kelso' },
    { value: 'Yanchep', label: 'Yanchep' },
    { value: 'Bentley', label: 'Bentley' },
    { value: 'Moe', label: 'Moe' },
    { value: 'Ayr', label: 'Ayr' },
    { value: 'Moranbah', label: 'Moranbah' },
    { value: 'Leeton', label: 'Leeton' },
    { value: 'Moss Vale', label: 'Moss Vale' },
    { value: 'Wallan', label: 'Wallan' },
    { value: 'Springwood', label: 'Springwood' },
    { value: 'Lesmurdie', label: 'Lesmurdie' },
    { value: 'Forbes', label: 'Forbes' },
    { value: 'Emu Plains', label: 'Emu Plains' },
    { value: 'Rye', label: 'Rye' },
    { value: 'Darley', label: 'Darley' },
    { value: 'Ararat', label: 'Ararat' },
    { value: 'Tweed Heads', label: 'Tweed Heads' },
    { value: 'Highfields', label: 'Highfields' },
    { value: 'Charters Towers', label: 'Charters Towers' },
    { value: 'Melton', label: 'Melton' },
    { value: 'Katoomba', label: 'Katoomba' },
    { value: 'Kilmore', label: 'Kilmore' },
    { value: 'Mooroopna', label: 'Mooroopna' },
    { value: 'Yarrawonga', label: 'Yarrawonga' },
    { value: 'Maryborough', label: 'Maryborough' },
    { value: 'Deniliquin', label: 'Deniliquin' },
    { value: 'Mandurah', label: 'Mandurah' },
    { value: 'Bli Bli', label: 'Bli Bli' },
    { value: 'Kiama', label: 'Kiama' },
    { value: 'Narre Warren North', label: 'Narre Warren North' },
    { value: 'Narrabri', label: 'Narrabri' },
    { value: 'Bairnsdale', label: 'Bairnsdale' },
    { value: 'Clifton Springs', label: 'Clifton Springs' },
    { value: 'North Tamborine', label: 'North Tamborine' },
    { value: 'Bargara', label: 'Bargara' },
    { value: 'Kingscliff', label: 'Kingscliff' },
    { value: 'Healesville', label: 'Healesville' },
    { value: 'Fremantle', label: 'Fremantle' },
    { value: 'Blaxland', label: 'Blaxland' },
    { value: 'Atherton', label: 'Atherton' },
    { value: 'Kyabram', label: 'Kyabram' },
    { value: 'Innisfail', label: 'Innisfail' },
    { value: 'Sanctuary Point', label: 'Sanctuary Point' },
    { value: 'Collie', label: 'Collie' },
    { value: 'Gatton', label: 'Gatton' },
    { value: 'Merrimac', label: 'Merrimac' },
    { value: 'Murwillumbah', label: 'Murwillumbah' },
    { value: 'Urraween', label: 'Urraween' },
    { value: 'Kyneton', label: 'Kyneton' },
    { value: 'Bongaree', label: 'Bongaree' },
    { value: 'Roma', label: 'Roma' },
    { value: 'Mount Cotton', label: 'Mount Cotton' },
    { value: 'Cootamundra', label: 'Cootamundra' },
    { value: 'Beerwah', label: 'Beerwah' },
    { value: 'Castlemaine', label: 'Castlemaine' },
    { value: 'Pottsville', label: 'Pottsville' },
    { value: 'Cooma', label: 'Cooma' },
    { value: 'Gordonvale', label: 'Gordonvale' },
    { value: 'Lysterfield', label: 'Lysterfield' },
    { value: 'Bomaderry', label: 'Bomaderry' },
    { value: 'Chinchilla', label: 'Chinchilla' },
    { value: 'Northam', label: 'Northam' },
    { value: 'Yass', label: 'Yass' },
    { value: 'Strathalbyn', label: 'Strathalbyn' },
    { value: 'Burpengary', label: 'Burpengary' },
    { value: 'Waterford', label: 'Waterford' },
    { value: 'Lennox Head', label: 'Lennox Head' },
    { value: 'Beaudesert', label: 'Beaudesert' },
    { value: 'Margaret River', label: 'Margaret River' },
    { value: 'Helensburgh', label: 'Helensburgh' },
    { value: 'Goondiwindi', label: 'Goondiwindi' },
    { value: 'Seymour', label: 'Seymour' },
    { value: 'Nambucca Heads', label: 'Nambucca Heads' },
    { value: 'Nuriootpa', label: 'Nuriootpa' },
    { value: 'Wauchope', label: 'Wauchope' },
    { value: 'Tumut', label: 'Tumut' },
    { value: 'Tuncurry', label: 'Tuncurry' },
    { value: 'Glen Innes', label: 'Glen Innes' },
    { value: 'Yamba', label: 'Yamba' },
    { value: 'Wentworth Falls', label: 'Wentworth Falls' },
    { value: 'South Grafton', label: 'South Grafton' },
    { value: 'Kurri Kurri', label: 'Kurri Kurri' },
    { value: 'Stawell', label: 'Stawell' },
    { value: 'Cobram', label: 'Cobram' },
    { value: 'Wynyard', label: 'Wynyard' },
    { value: 'Naracoorte', label: 'Naracoorte' },
    { value: 'North Mackay', label: 'North Mackay' },
    { value: 'Cannington', label: 'Cannington' },
    { value: 'Woodend', label: 'Woodend' },
    { value: 'Dromana', label: 'Dromana' },
    { value: 'Emerald', label: 'Emerald' },
    { value: 'Biloela', label: 'Biloela' },
    { value: 'Alstonville', label: 'Alstonville' },
    { value: 'Cannonvale', label: 'Cannonvale' },
    { value: 'Point Vernon', label: 'Point Vernon' },
    { value: 'Palmwoods', label: 'Palmwoods' },
    { value: 'Scone', label: 'Scone' },
    { value: 'Whittlesea', label: 'Whittlesea' },
    { value: 'East Ballina', label: 'East Ballina' },
    { value: 'Sarina', label: 'Sarina' },
    { value: 'Byron Bay', label: 'Byron Bay' },
    { value: 'Corowa', label: 'Corowa' },
    { value: 'Richmond', label: 'Richmond' },
    { value: 'Cooranbong', label: 'Cooranbong' },
    { value: 'Bullsbrook', label: 'Bullsbrook' },
    { value: 'Inverloch', label: 'Inverloch' },
    { value: 'New Norfolk', label: 'New Norfolk' },
    { value: 'Stanthorpe', label: 'Stanthorpe' },
    { value: 'Wingham', label: 'Wingham' },
    { value: 'Irymple', label: 'Irymple' },
    { value: 'Dunsborough', label: 'Dunsborough' },
    { value: 'Kununurra', label: 'Kununurra' },
    { value: 'Smithfield Heights', label: 'Smithfield Heights' },
    { value: 'Woolgoolga', label: 'Woolgoolga' },
    { value: 'Bannockburn', label: 'Bannockburn' },
    { value: 'Maffra', label: 'Maffra' },
    { value: 'Tannum Sands', label: 'Tannum Sands' },
    { value: 'Ocean Shores', label: 'Ocean Shores' },
    { value: 'Howard Springs', label: 'Howard Springs' },
    { value: 'Leongatha', label: 'Leongatha' },
    { value: 'Worragee', label: 'Worragee' },
    { value: 'Tahmoor', label: 'Tahmoor' },
    { value: 'Red Cliffs', label: 'Red Cliffs' },
    { value: 'Glenbrook', label: 'Glenbrook' },
    { value: 'McMinns Lagoon', label: 'McMinns Lagoon' },
    { value: 'Kiama Downs', label: 'Kiama Downs' },
    { value: 'Hazelbrook', label: 'Hazelbrook' },
    { value: 'Wonthaggi', label: 'Wonthaggi' },
    { value: 'Junee', label: 'Junee' },
    { value: 'Pinjarra', label: 'Pinjarra' },
    { value: 'Encounter Bay', label: 'Encounter Bay' },
    { value: 'Nairne', label: 'Nairne' },
    { value: 'Cowes', label: 'Cowes' },
    { value: 'Boulder', label: 'Boulder' },
    { value: 'Picton', label: 'Picton' },
    { value: 'Salamander Bay', label: 'Salamander Bay' },
    { value: 'Lakes Entrance', label: 'Lakes Entrance' },
    { value: 'Mansfield', label: 'Mansfield' },
    { value: 'Churchill', label: 'Churchill' },
    { value: 'Bucasia', label: 'Bucasia' },
    { value: 'Boyne Island', label: 'Boyne Island' },
    { value: 'Blackwater', label: 'Blackwater' },
    { value: 'Millicent', label: 'Millicent' },
    { value: 'Oakey', label: 'Oakey' },
    { value: 'Temora', label: 'Temora' },
    { value: 'Narromine', label: 'Narromine' },
    { value: 'Ningi', label: 'Ningi' },
    { value: 'Bega', label: 'Bega' },
    { value: 'Mount Low', label: 'Mount Low' },
    { value: 'Leura', label: 'Leura' },
    { value: 'Renmark', label: 'Renmark' },
    { value: 'South West Rocks', label: 'South West Rocks' },
    { value: 'Tanunda', label: 'Tanunda' },
    { value: 'Kadina', label: 'Kadina' },
    { value: 'Newman', label: 'Newman' },
    { value: 'Glenella', label: 'Glenella' },
    { value: 'Roxby Downs', label: 'Roxby Downs' },
    { value: 'Numurkah', label: 'Numurkah' },
    { value: 'Korumburra', label: 'Korumburra' },
    { value: 'Rasmussen', label: 'Rasmussen' },
    { value: 'Tatura', label: 'Tatura' },
    { value: 'Carnarvon', label: 'Carnarvon' },
    { value: 'Romsey', label: 'Romsey' },
    { value: 'Blackheath', label: 'Blackheath' },
    { value: 'Bargo', label: 'Bargo' },
    { value: 'Old Bar', label: 'Old Bar' },
    { value: 'Narrandera', label: 'Narrandera' },
    { value: 'Ingham', label: 'Ingham' },
    { value: 'Manjimup', label: 'Manjimup' },
    { value: 'George Town', label: 'George Town' },
    { value: 'Wyong', label: 'Wyong' },
    { value: 'Broadford', label: 'Broadford' },
    { value: 'Drysdale', label: 'Drysdale' },
    { value: 'Narrogin', label: 'Narrogin' },
    { value: 'Cockatoo', label: 'Cockatoo' },
    { value: 'Victor Harbor', label: 'Victor Harbor' },
    { value: 'Moama', label: 'Moama' },
    { value: 'Bungendore', label: 'Bungendore' },
    { value: 'Latrobe', label: 'Latrobe' },
    { value: 'Beachmere', label: 'Beachmere' },
    { value: 'Berri', label: 'Berri' },
    { value: 'Wellington', label: 'Wellington' },
    { value: 'Tenterfield', label: 'Tenterfield' },
    { value: 'Thirlmere', label: 'Thirlmere' },
    { value: 'Legana', label: 'Legana' },
    { value: 'Faulconbridge', label: 'Faulconbridge' },
    { value: 'The Entrance', label: 'The Entrance' },
    { value: 'Cobar', label: 'Cobar' },
    { value: 'Wallaroo', label: 'Wallaroo' },
    { value: 'Moruya', label: 'Moruya' },
    { value: 'Gerringong', label: 'Gerringong' },
    { value: 'Sandstone Point', label: 'Sandstone Point' },
    { value: 'Tambourine', label: 'Tambourine' },
    { value: 'Margate', label: 'Margate' },
    { value: 'Trafalgar', label: 'Trafalgar' },
    { value: 'Somerset', label: 'Somerset' },
    { value: 'Marian', label: 'Marian' },
    { value: 'Weipa', label: 'Weipa' },
    { value: 'Kerang', label: 'Kerang' },
    { value: 'Westbrook', label: 'Westbrook' },
    { value: 'Smithton', label: 'Smithton' },
    { value: 'Longford', label: 'Longford' },
    { value: 'Karana Downs', label: 'Karana Downs' },
    { value: 'Beechworth', label: 'Beechworth' },
    { value: 'Penguin', label: 'Penguin' },
    { value: 'Anna Bay', label: 'Anna Bay' },
    { value: 'Loxton', label: 'Loxton' },
    { value: 'Pearcedale', label: 'Pearcedale' },
    { value: 'Landsborough', label: 'Landsborough' },
    { value: 'Laidley', label: 'Laidley' },
    { value: 'Wonga Park', label: 'Wonga Park' },
    { value: 'Peregian Beach', label: 'Peregian Beach' },
    { value: 'Cooroy', label: 'Cooroy' },
    { value: 'Bellingen', label: 'Bellingen' },
    { value: 'Riddell', label: 'Riddell' },
    { value: 'Suffolk Park', label: 'Suffolk Park' },
    { value: 'Buninyong', label: 'Buninyong' },
    { value: 'Weston', label: 'Weston' },
    { value: 'Katanning', label: 'Katanning' },
    { value: 'Bellbrae', label: 'Bellbrae' },
    { value: 'Sawtell', label: 'Sawtell' },
    { value: 'Silverdale', label: 'Silverdale' },
    { value: 'Tallebudgera', label: 'Tallebudgera' },
    { value: 'Bay View', label: 'Bay View' },
    { value: 'Portarlington', label: 'Portarlington' },
    { value: 'Nanango', label: 'Nanango' },
    { value: 'Logan Village', label: 'Logan Village' },
    { value: 'Koo-Wee-Rup', label: 'Koo-Wee-Rup' },
    { value: 'Glass House Mountains', label: 'Glass House Mountains' },
    { value: 'Sussex Inlet', label: 'Sussex Inlet' },
    { value: 'Proserpine', label: 'Proserpine' },
    { value: 'Merimbula', label: 'Merimbula' },
    { value: 'Scarness', label: 'Scarness' },
    { value: 'Port Douglas', label: 'Port Douglas' },
    { value: 'Gosford', label: 'Gosford' },
    { value: 'Bridgewater', label: 'Bridgewater' },
    { value: 'Lake Cathie', label: 'Lake Cathie' },
    { value: 'Condobolin', label: 'Condobolin' },
    { value: 'Paynesville', label: 'Paynesville' },
    { value: 'Woodford', label: 'Woodford' },
    { value: 'Maddingley', label: 'Maddingley' },
    { value: 'Hurstbridge', label: 'Hurstbridge' },
    { value: 'Quirindi', label: 'Quirindi' },
    { value: 'Maleny', label: 'Maleny' },
    { value: 'Calliope', label: 'Calliope' },
    { value: 'North Beach', label: 'North Beach' },
    { value: 'Walkerston', label: 'Walkerston' },
    { value: 'Blayney', label: 'Blayney' },
    { value: 'Camperdown', label: 'Camperdown' },
    { value: 'Aldgate', label: 'Aldgate' },
    { value: 'Port Fairy', label: 'Port Fairy' },
    { value: 'Tyabb', label: 'Tyabb' },
    { value: 'Lowood', label: 'Lowood' },
    { value: 'Charleville', label: 'Charleville' },
    { value: 'Derby', label: 'Derby' },
    { value: 'Mooloolah', label: 'Mooloolah' },
    { value: 'Pittsworth', label: 'Pittsworth' },
    { value: 'Vincentia', label: 'Vincentia' },
    { value: 'Coonabarabran', label: 'Coonabarabran' },
    { value: 'Euroa', label: 'Euroa' },
    { value: 'Oberon', label: 'Oberon' },
    { value: 'Woombye', label: 'Woombye' },
    { value: 'Nhulunbuy', label: 'Nhulunbuy' },
    { value: 'Camden', label: 'Camden' },
    { value: 'Murrumbateman', label: 'Murrumbateman' },
    { value: 'Fernvale', label: 'Fernvale' },
    { value: 'East Hills', label: 'East Hills' },
    { value: 'Bohle Plains', label: 'Bohle Plains' },
    { value: 'Junortoun', label: 'Junortoun' },
    { value: 'Myrtleford', label: 'Myrtleford' },
    { value: 'Crib Point', label: 'Crib Point' },
    { value: 'Marcoola', label: 'Marcoola' },
    { value: 'Mullumbimby', label: 'Mullumbimby' },
    { value: 'Creswick', label: 'Creswick' },
    { value: 'Clare', label: 'Clare' },
    { value: 'Tura Beach', label: 'Tura Beach' },
    { value: 'Eden', label: 'Eden' },
    { value: 'West Wyalong', label: 'West Wyalong' },
    { value: 'Gilgandra', label: 'Gilgandra' },
    { value: 'Rochester', label: 'Rochester' },
    { value: 'McLaren Vale', label: 'McLaren Vale' },
    { value: 'Miners Rest', label: 'Miners Rest' },
    { value: 'Robinvale', label: 'Robinvale' },
    { value: 'Wilton', label: 'Wilton' },
    { value: 'Riverview', label: 'Riverview' },
    { value: 'Bogangar', label: 'Bogangar' },
    { value: 'Shoalhaven Heads', label: 'Shoalhaven Heads' },
    { value: 'Saint George', label: 'Saint George' },
    { value: 'Little Hampton', label: 'Little Hampton' },
    { value: 'Clermont', label: 'Clermont' },
    { value: 'Home Hill', label: 'Home Hill' },
    { value: 'Central Coast', label: 'Central Coast' },
    { value: 'Kuranda', label: 'Kuranda' },
    { value: 'Wilberforce', label: 'Wilberforce' },
    { value: 'Tom Price', label: 'Tom Price' },
    { value: 'Urunga', label: 'Urunga' },
    { value: 'Dysart', label: 'Dysart' },
    { value: 'Two Rocks', label: 'Two Rocks' },
    { value: 'Ballan', label: 'Ballan' },
    { value: 'Gloucester', label: 'Gloucester' },
    { value: 'Bonny Hills', label: 'Bonny Hills' },
    { value: 'Longreach', label: 'Longreach' },
    { value: 'Stirling', label: 'Stirling' },
    { value: 'Perth', label: 'Perth' },
    { value: 'Bordertown', label: 'Bordertown' },
    { value: 'Lewiston', label: 'Lewiston' },
    { value: 'Waroona', label: 'Waroona' },
    { value: 'Leschenault', label: 'Leschenault' },
    { value: 'Terranora', label: 'Terranora' },
    { value: 'Kapunda', label: 'Kapunda' },
    { value: 'Woori Yallock', label: 'Woori Yallock' },
    { value: 'Saint Georges Basin', label: 'Saint Georges Basin' },
    { value: 'Pomona', label: 'Pomona' },
    { value: 'Sorell', label: 'Sorell' },
    { value: 'Tea Gardens', label: 'Tea Gardens' },
    { value: 'Culburra', label: 'Culburra' },
    { value: 'Yarra Glen', label: 'Yarra Glen' },
    { value: 'Beaconsfield Upper', label: 'Beaconsfield Upper' },
    { value: 'Morisset', label: 'Morisset' },
    { value: 'Cohuna', label: 'Cohuna' },
    { value: 'Merredin', label: 'Merredin' },
    { value: 'Deloraine', label: 'Deloraine' },
    { value: 'Evans Head', label: 'Evans Head' },
    { value: 'Rosewood', label: 'Rosewood' },
    { value: 'Greta', label: 'Greta' },
    { value: 'Wollongbar', label: 'Wollongbar' },
    { value: 'Donnybrook', label: 'Donnybrook' },
    { value: 'McCrae', label: 'McCrae' },
    { value: 'Angle Vale', label: 'Angle Vale' },
    { value: 'Bridgetown', label: 'Bridgetown' },
    { value: 'North Wonthaggi', label: 'North Wonthaggi' },
    { value: 'Heathcote', label: 'Heathcote' },
    { value: 'Howlong', label: 'Howlong' },
    { value: 'Williamstown', label: 'Williamstown' },
    { value: 'Harvey', label: 'Harvey' },
    { value: 'Coonamble', label: 'Coonamble' },
    { value: 'Uralla', label: 'Uralla' },
    { value: 'Bundanoon', label: 'Bundanoon' },
    { value: 'Cloncurry', label: 'Cloncurry' },
    { value: 'Tolga', label: 'Tolga' },
    { value: 'Huonville', label: 'Huonville' },
    { value: 'Merbein', label: 'Merbein' },
    { value: 'Alexandra', label: 'Alexandra' },
    { value: 'Waikerie', label: 'Waikerie' },
    { value: 'Point Lonsdale', label: 'Point Lonsdale' },
    { value: 'Hill Top', label: 'Hill Top' },
    { value: 'Stirling North', label: 'Stirling North' },
    { value: 'Hahndorf', label: 'Hahndorf' },
    { value: 'Berry', label: 'Berry' },
    { value: 'Burnett Heads', label: 'Burnett Heads' },
    { value: 'Moore Park', label: 'Moore Park' },
    { value: 'Burradoo', label: 'Burradoo' },
    { value: 'Mannum', label: 'Mannum' },
    { value: 'Wooroloo', label: 'Wooroloo' },
    { value: 'Crookwell', label: 'Crookwell' },
    { value: 'Appin', label: 'Appin' },
    { value: 'Cooloola Cove', label: 'Cooloola Cove' },
    { value: 'Cooktown', label: 'Cooktown' },
    { value: 'Jindabyne', label: 'Jindabyne' },
    { value: 'Maclean', label: 'Maclean' },
    { value: 'Stratford', label: 'Stratford' },
    { value: 'Lawson', label: 'Lawson' },
    { value: 'Thursday Island', label: 'Thursday Island' },
    { value: 'Woodside', label: 'Woodside' },
    { value: 'Narooma', label: 'Narooma' },
    { value: 'Macksville', label: 'Macksville' },
    { value: 'Molong', label: 'Molong' },
    { value: 'Grenfell', label: 'Grenfell' },
    { value: 'Yarrabah Aboriginal Community', label: 'Yarrabah Aboriginal Community' },
    { value: 'Denmark', label: 'Denmark' },
    { value: 'Bonville', label: 'Bonville' },
    { value: 'Walcha', label: 'Walcha' },
    { value: 'Manilla', label: 'Manilla' },
    { value: 'Yarra Junction', label: 'Yarra Junction' },
    { value: 'Daylesford', label: 'Daylesford' },
    { value: 'York', label: 'York' },
    { value: 'Anglesea', label: 'Anglesea' },
    { value: 'Kambalda', label: 'Kambalda' },
    { value: 'Lobethal', label: 'Lobethal' },
    { value: 'The Oaks', label: 'The Oaks' },
    { value: 'Gulgong', label: 'Gulgong' },
    { value: 'Finley', label: 'Finley' },
    { value: 'Capel', label: 'Capel' },
    { value: 'Korora', label: 'Korora' },
    { value: 'Exmouth', label: 'Exmouth' },
    { value: 'Boonah', label: 'Boonah' },
    { value: 'Saint Leonards', label: 'Saint Leonards' },
    { value: 'Vasse', label: 'Vasse' },
    { value: 'Aberdare', label: 'Aberdare' },
    { value: 'Bunyip', label: 'Bunyip' },
    { value: 'Dodges Ferry', label: 'Dodges Ferry' },
    { value: 'Lancefield', label: 'Lancefield' },
    { value: 'Palm Island', label: 'Palm Island' },
    { value: 'Currie', label: 'Currie' },


];

export default options
